/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as AdminAuthRouteImport } from './routes/admin/auth'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupCredentialsRouteImport } from './routes/setup.credentials'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoBranchesRouteImport } from './routes/$owner.$repo.branches'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner.$repo.settings'
import { Route as OwnerRepoTagsRouteImport } from './routes/$owner.$repo.tags'
import { Route as SettingsTokensNewRouteImport } from './routes/settings/tokens.new'
import { Route as OwnerRepoBlameSplatRouteImport } from './routes/$owner.$repo.blame.$'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner.$repo.blob.$'
import { Route as OwnerRepoCommitShaRouteImport } from './routes/$owner.$repo.commit.$sha'
import { Route as OwnerRepoCommitsSplatRouteImport } from './routes/$owner.$repo.commits.$'
import { Route as OwnerRepoCompareSplatRouteImport } from './routes/$owner.$repo.compare.$'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner.$repo.tree.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCredentialsRoute = SetupCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SetupRoute,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBranchesRoute = OwnerRepoBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoTagsRoute = OwnerRepoTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const SettingsTokensNewRoute = SettingsTokensNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsTokensRoute,
} as any)
const OwnerRepoBlameSplatRoute = OwnerRepoBlameSplatRouteImport.update({
  id: '/blame/$',
  path: '/blame/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitShaRoute = OwnerRepoCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsSplatRoute = OwnerRepoCommitsSplatRouteImport.update({
  id: '/commits/$',
  path: '/commits/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCompareSplatRoute = OwnerRepoCompareSplatRouteImport.update({
  id: '/compare/$',
  path: '/compare/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tokens': typeof SettingsTokensRouteWithChildren
  '/setup/credentials': typeof SetupCredentialsRoute
  '/setup/': typeof SetupIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/settings/tokens/new': typeof SettingsTokensNewRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/admin/auth': typeof AdminAuthRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tokens': typeof SettingsTokensRouteWithChildren
  '/setup/credentials': typeof SetupCredentialsRoute
  '/setup': typeof SetupIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/settings/tokens/new': typeof SettingsTokensNewRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tokens': typeof SettingsTokensRouteWithChildren
  '/setup/credentials': typeof SetupCredentialsRoute
  '/setup/': typeof SetupIndexRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/settings/tokens/new': typeof SettingsTokensNewRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/status'
    | '/verify'
    | '/$owner/$repo'
    | '/admin/auth'
    | '/settings/profile'
    | '/settings/tokens'
    | '/setup/credentials'
    | '/setup/'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/tags'
    | '/settings/tokens/new'
    | '/$owner/$repo/'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/signup'
    | '/status'
    | '/verify'
    | '/admin/auth'
    | '/settings/profile'
    | '/settings/tokens'
    | '/setup/credentials'
    | '/setup'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/tags'
    | '/settings/tokens/new'
    | '/$owner/$repo'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/tree/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/status'
    | '/verify'
    | '/$owner/$repo'
    | '/admin/auth'
    | '/settings/profile'
    | '/settings/tokens'
    | '/setup/credentials'
    | '/setup/'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/tags'
    | '/settings/tokens/new'
    | '/$owner/$repo/'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRouteWithChildren
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  VerifyRoute: typeof VerifyRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  AdminAuthRoute: typeof AdminAuthRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTokensRoute: typeof SettingsTokensRouteWithChildren
}

declare module '@octanejs/tanstack-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/credentials': {
      id: '/setup/credentials'
      path: '/credentials'
      fullPath: '/setup/credentials'
      preLoaderRoute: typeof SetupCredentialsRouteImport
      parentRoute: typeof SetupRoute
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/branches': {
      id: '/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof OwnerRepoBranchesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/tags': {
      id: '/$owner/$repo/tags'
      path: '/tags'
      fullPath: '/$owner/$repo/tags'
      preLoaderRoute: typeof OwnerRepoTagsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/settings/tokens/new': {
      id: '/settings/tokens/new'
      path: '/new'
      fullPath: '/settings/tokens/new'
      preLoaderRoute: typeof SettingsTokensNewRouteImport
      parentRoute: typeof SettingsTokensRoute
    }
    '/$owner/$repo/blame/$': {
      id: '/$owner/$repo/blame/$'
      path: '/blame/$'
      fullPath: '/$owner/$repo/blame/$'
      preLoaderRoute: typeof OwnerRepoBlameSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commit/$sha': {
      id: '/$owner/$repo/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/$owner/$repo/commit/$sha'
      preLoaderRoute: typeof OwnerRepoCommitShaRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits/$': {
      id: '/$owner/$repo/commits/$'
      path: '/commits/$'
      fullPath: '/$owner/$repo/commits/$'
      preLoaderRoute: typeof OwnerRepoCommitsSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/compare/$': {
      id: '/$owner/$repo/compare/$'
      path: '/compare/$'
      fullPath: '/$owner/$repo/compare/$'
      preLoaderRoute: typeof OwnerRepoCompareSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface SetupRouteChildren {
  SetupCredentialsRoute: typeof SetupCredentialsRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCredentialsRoute: SetupCredentialsRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface OwnerRepoRouteChildren {
  OwnerRepoBranchesRoute: typeof OwnerRepoBranchesRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerRepoTagsRoute: typeof OwnerRepoTagsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlameSplatRoute: typeof OwnerRepoBlameSplatRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoCommitShaRoute: typeof OwnerRepoCommitShaRoute
  OwnerRepoCommitsSplatRoute: typeof OwnerRepoCommitsSplatRoute
  OwnerRepoCompareSplatRoute: typeof OwnerRepoCompareSplatRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoBranchesRoute: OwnerRepoBranchesRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerRepoTagsRoute: OwnerRepoTagsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlameSplatRoute: OwnerRepoBlameSplatRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoCommitShaRoute: OwnerRepoCommitShaRoute,
  OwnerRepoCommitsSplatRoute: OwnerRepoCommitsSplatRoute,
  OwnerRepoCompareSplatRoute: OwnerRepoCompareSplatRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

interface SettingsTokensRouteChildren {
  SettingsTokensNewRoute: typeof SettingsTokensNewRoute
}

const SettingsTokensRouteChildren: SettingsTokensRouteChildren = {
  SettingsTokensNewRoute: SettingsTokensNewRoute,
}

const SettingsTokensRouteWithChildren = SettingsTokensRoute._addFileChildren(
  SettingsTokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRouteWithChildren,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  VerifyRoute: VerifyRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  AdminAuthRoute: AdminAuthRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTokensRoute: SettingsTokensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@octanejs/tanstack-start'
declare module '@octanejs/tanstack-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
