# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1.0"

gem "rails", "~> 8.0"
gem "puma", ">= 6.0"
gem "sqlite3", ">= 2.1"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :development do
  gem "web-console"
end
