/** AUTO-GENERATED by `cargo run -p octanest-api --bin rpc-gen` — do not edit by hand. */

export const RPC_VERSION = 1 as const;
export const RPC_VERSION_HEADER = "Octanest-RPC-Version" as const;

export type AppError = {
  code: string;
  message: string;
  data?: unknown;
};

export type HealthResponse = {
  status: string;
  version: string;
  database: string;
};

export type EchoRequest = {
  message: string;
};

export type EchoResponse = {
  message: string;
};

export type DbProbeResponse = {
  dialect: string;
  probe_count: number;
  probed_at: string;
};

export type ProviderMode = "local" | "workos" | "oidc";

export type EmailProviderKind = "log" | "smtp" | "resend";

export type UserRole = "user" | "admin" | "sys-admin";

export type UserPublic = {
  id: string;
  email: string;
  username: string;
  display_name: string;
  bio: string;
  avatar_url?: string | null;
  role: UserRole;
  profile_incomplete: boolean;
  email_verified: boolean;
  must_change_credentials: boolean;
};

export type BootstrapStatus = {
  needs_setup: boolean;
};

export type BootstrapSetupRequest = {
  email: string;
  username: string;
  password: string;
};

export type SignupRequest = {
  email: string;
  username: string;
  password: string;
};

export type LoginRequest = {
  identifier: string;
  password: string;
  remember_me: boolean;
};

export type VerifyRequest = {
  token?: string | null;
  code?: string | null;
};

export type RequestPasswordResetRequest = {
  email: string;
};

export type ResetPasswordRequest = {
  token?: string | null;
  code?: string | null;
  password: string;
};

export type ProviderConfigPublic = {
  mode: ProviderMode;
  allow_signup: boolean;
};

export type UpdateProfileRequest = {
  display_name: string;
  username: string;
  bio: string;
};

export type AuthSettingsPublic = {
  provider_mode: ProviderMode;
  email_provider: EmailProviderKind;
  from_address?: string | null;
  workos_client_id?: string | null;
  oidc_issuer?: string | null;
  oidc_client_id?: string | null;
  smtp_configured: boolean;
  resend_configured: boolean;
  workos_api_key_configured: boolean;
  oidc_client_secret_configured: boolean;
  allow_signup: boolean;
};

export type UpdateAuthSettingsRequest = {
  provider_mode: ProviderMode;
  email_provider: EmailProviderKind;
  from_address?: string | null;
  oidc_issuer?: string | null;
  oidc_client_id?: string | null;
  workos_client_id?: string | null;
  allow_signup?: boolean;
};

export type RpcOk<T> = { ok: true; data: T };
export type RpcErr = { ok: false; error: AppError };
export type RpcResult<T> = RpcOk<T> | RpcErr;

export type CreateClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
  credentials?: RequestCredentials;
};

async function rpcCall<T>(
  opts: CreateClientOptions,
  procedure: string,
  input: unknown,
): Promise<RpcResult<T>> {
  const fetchFn = opts.fetch ?? fetch;
  const url = `${opts.baseUrl.replace(/\/$/, "")}/api/rpc`;
  const res = await fetchFn(url, {
    method: "POST",
    credentials: opts.credentials ?? "include",
    headers: {
      "content-type": "application/json",
      [RPC_VERSION_HEADER]: String(RPC_VERSION),
    },
    body: JSON.stringify({ procedure, input }),
  });
  return (await res.json()) as RpcResult<T>;
}

export function createClient(opts: CreateClientOptions) {
  return {
    system: {
      health: () => rpcCall<HealthResponse>(opts, "system.health", {}),
      echo: (input: EchoRequest) => rpcCall<EchoResponse>(opts, "system.echo", input),
      dbProbe: () => rpcCall<DbProbeResponse>(opts, "system.db_probe", {}),
    },
    auth: {
      signup: (input: SignupRequest) => rpcCall<UserPublic>(opts, "auth.signup", input),
      login: (input: LoginRequest) => rpcCall<UserPublic>(opts, "auth.login", input),
      logout: () => rpcCall<{ ok: boolean }>(opts, "auth.logout", {}),
      logoutAll: () => rpcCall<{ ok: boolean }>(opts, "auth.logout_all", {}),
      me: () => rpcCall<UserPublic>(opts, "auth.me", {}),
      providerConfig: () =>
        rpcCall<ProviderConfigPublic>(opts, "auth.provider_config", {}),
      bootstrapStatus: () =>
        rpcCall<BootstrapStatus>(opts, "auth.bootstrap_status", {}),
      bootstrapSetup: (input: BootstrapSetupRequest) =>
        rpcCall<UserPublic>(opts, "auth.bootstrap_setup", input),
      verify: (input: VerifyRequest) => rpcCall<UserPublic>(opts, "auth.verify", input),
      requestVerify: () => rpcCall<{ ok: boolean }>(opts, "auth.request_verify", {}),
      resendVerify: () => rpcCall<{ ok: boolean }>(opts, "auth.resend_verify", {}),
      requestPasswordReset: (input: RequestPasswordResetRequest) =>
        rpcCall<{ ok: boolean }>(opts, "auth.request_password_reset", input),
      resetPassword: (input: ResetPasswordRequest) =>
        rpcCall<UserPublic>(opts, "auth.reset_password", input),
      privilegedPing: () =>
        rpcCall<{ ok: boolean }>(opts, "auth.dev.privileged_ping", {}),
    },
    user: {
      getProfile: () => rpcCall<UserPublic>(opts, "user.get_profile", {}),
      updateProfile: (input: UpdateProfileRequest) =>
        rpcCall<UserPublic>(opts, "user.update_profile", input),
    },
    admin: {
      auth: {
        getSettings: () =>
          rpcCall<AuthSettingsPublic>(opts, "admin.auth.get_settings", {}),
        updateSettings: (input: UpdateAuthSettingsRequest) =>
          rpcCall<AuthSettingsPublic>(opts, "admin.auth.update_settings", input),
      },
    },
  };
}

export type OctanestClient = ReturnType<typeof createClient>;

/** TanStack Query helpers — pass a client from createClient(). */
export function systemHealthQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["system", "health"] as const,
    queryFn: async () => {
      const res = await client.system.health();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function systemEchoMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["system", "echo"] as const,
    mutationFn: async (input: EchoRequest) => {
      const res = await client.system.echo(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function systemDbProbeQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["system", "dbProbe"] as const,
    queryFn: async () => {
      const res = await client.system.dbProbe();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authMeQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["auth", "me"] as const,
    queryFn: async () => {
      const res = await client.auth.me();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authProviderConfigQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["auth", "providerConfig"] as const,
    queryFn: async () => {
      const res = await client.auth.providerConfig();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authSignupMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "signup"] as const,
    mutationFn: async (input: SignupRequest) => {
      const res = await client.auth.signup(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLoginMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "login"] as const,
    mutationFn: async (input: LoginRequest) => {
      const res = await client.auth.login(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLogoutMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "logout"] as const,
    mutationFn: async () => {
      const res = await client.auth.logout();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLogoutAllMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "logoutAll"] as const,
    mutationFn: async () => {
      const res = await client.auth.logoutAll();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function userGetProfileQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["user", "getProfile"] as const,
    queryFn: async () => {
      const res = await client.user.getProfile();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function userUpdateProfileMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["user", "updateProfile"] as const,
    mutationFn: async (input: UpdateProfileRequest) => {
      const res = await client.user.updateProfile(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function adminAuthGetSettingsQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["admin", "auth", "getSettings"] as const,
    queryFn: async () => {
      const res = await client.admin.auth.getSettings();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function adminAuthUpdateSettingsMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["admin", "auth", "updateSettings"] as const,
    mutationFn: async (input: UpdateAuthSettingsRequest) => {
      const res = await client.admin.auth.updateSettings(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

/** Alias helpers matching CONTEXT D-21 naming. */
export const queryOptions = {
  systemHealth: systemHealthQueryOptions,
  systemDbProbe: systemDbProbeQueryOptions,
  authMe: authMeQueryOptions,
  authProviderConfig: authProviderConfigQueryOptions,
  userGetProfile: userGetProfileQueryOptions,
  adminAuthGetSettings: adminAuthGetSettingsQueryOptions,
};
export const mutationOptions = {
  systemEcho: systemEchoMutationOptions,
  authSignup: authSignupMutationOptions,
  authLogin: authLoginMutationOptions,
  authLogout: authLogoutMutationOptions,
  authLogoutAll: authLogoutAllMutationOptions,
  userUpdateProfile: userUpdateProfileMutationOptions,
  adminAuthUpdateSettings: adminAuthUpdateSettingsMutationOptions,
};
