/** AUTO-GENERATED by `cargo run -p octanest-api --bin rpc-gen` — do not edit by hand. */

export const RPC_VERSION = 1 as const;
export const RPC_VERSION_HEADER = "Octanest-RPC-Version" as const;

export type AppError = {
  code: string;
  message: string;
  data?: unknown;
};

export type HealthResponse = {
  status: string;
  version: string;
  database: string;
};

export type EchoRequest = {
  message: string;
};

export type EchoResponse = {
  message: string;
};

export type DbProbeResponse = {
  dialect: string;
  probe_count: number;
  probed_at: string;
};

export type ProviderMode = "local" | "workos" | "oidc";

export type EmailProviderKind = "log" | "smtp" | "resend";

export type UserRole = "user" | "admin" | "sys-admin";

export type UserPublic = {
  id: string;
  email: string;
  username: string;
  display_name: string;
  bio: string;
  avatar_url?: string | null;
  role: UserRole;
  profile_incomplete: boolean;
  email_verified: boolean;
  must_change_credentials: boolean;
  default_branch: string;
};

export type BootstrapStatus = {
  needs_setup: boolean;
};

export type BootstrapSetupRequest = {
  email: string;
  username: string;
  password: string;
  allow_signup?: boolean;
  provider_mode?: ProviderMode;
  oidc_issuer?: string | null;
  oidc_client_id?: string | null;
  workos_client_id?: string | null;
};

export type FactoryResetRequest = {
  confirmation: string;
  /** Omit → database_only (D-34). */
  scope?: "database_only" | "database_and_repositories";
};

export type FactoryResetResponse = {
  ok: boolean;
  needs_setup: boolean;
};

export type RepoGcRequest = {
  owner?: string | null;
  name?: string | null;
};

export type RepoGcResponse = {
  ok: boolean;
  gc_count: number;
  error_count: number;
};

export type ConfirmAdminCredentialsRequest = {
  username: string;
  email?: string | null;
  password?: string | null;
  keep_password?: boolean;
};

export type SignupRequest = {
  email: string;
  username: string;
  password: string;
};

export type LoginRequest = {
  identifier: string;
  password: string;
  remember_me: boolean;
};

export type VerifyRequest = {
  token?: string | null;
  code?: string | null;
};

export type RequestPasswordResetRequest = {
  email: string;
};

export type ResetPasswordRequest = {
  token?: string | null;
  code?: string | null;
  password: string;
};

export type ProviderConfigPublic = {
  mode: ProviderMode;
  allow_signup: boolean;
};

export type RepoVisibility = "public" | "private";

export type OwnerType = "user" | "org";

export type UpdateProfileRequest = {
  display_name: string;
  username: string;
  bio: string;
  default_branch?: string | null;
};

export type UserLookupRequest = {
  prefix: string;
};

export type UserLookupHit = {
  username: string;
  display_name: string;
  avatar_url?: string | null;
};

export type UserLookupResponse = {
  users: UserLookupHit[];
};

export type AuthSettingsPublic = {
  provider_mode: ProviderMode;
  email_provider: EmailProviderKind;
  from_address?: string | null;
  workos_client_id?: string | null;
  oidc_issuer?: string | null;
  oidc_client_id?: string | null;
  smtp_configured: boolean;
  resend_configured: boolean;
  workos_api_key_configured: boolean;
  oidc_client_secret_configured: boolean;
  allow_signup: boolean;
  default_visibility: RepoVisibility;
};

export type UpdateAuthSettingsRequest = {
  provider_mode: ProviderMode;
  email_provider: EmailProviderKind;
  from_address?: string | null;
  oidc_issuer?: string | null;
  oidc_client_id?: string | null;
  workos_client_id?: string | null;
  allow_signup?: boolean;
  default_visibility?: RepoVisibility;
};

export type CreateRepoRequest = {
  name: string;
  description?: string | null;
  visibility?: RepoVisibility | null;
  stack_id?: string | null;
  license_id?: string | null;
  gitignore_id?: string | null;
  owner?: string | null;
};

export type RepoTemplateOption = {
  id: string;
  label: string;
  group: string;
  description: string;
  default_gitignore?: string | null;
};

export type RepoCreateDefaults = {
  default_visibility: RepoVisibility;
  stacks: RepoTemplateOption[];
  gitignores: RepoTemplateOption[];
};

export type RepoPublic = {
  id: string;
  owner_id: string;
  owner_type: OwnerType;
  owner_username: string;
  name: string;
  description: string;
  visibility: RepoVisibility;
  default_branch: string;
  updated_at: string;
  can_admin: boolean;
  can_write: boolean;
};

export type RepoListMineResponse = {
  repos: RepoPublic[];
};

export type RepoGetRequest = {
  owner: string;
  name: string;
};

export type RepoTreeRequest = {
  owner: string;
  name: string;
  ref: string;
  path?: string | null;
};

export type RepoTreeEntry = {
  mode: string;
  kind: string;
  oid: string;
  name: string;
};

export type RepoTreeResponse = {
  empty: boolean;
  ref: string;
  path: string;
  entries: RepoTreeEntry[];
};

export type RepoBlobRequest = {
  owner: string;
  name: string;
  ref: string;
  path: string;
};

export type RepoBlobResponse = {
  path: string;
  ref: string;
  size: number;
  truncated: boolean;
  is_binary: boolean;
  encoding: string;
  content?: string | null;
  soft_max_bytes: number;
};

export type RepoRefEntry = {
  name: string;
  oid: string;
};

export type RepoRefsResponse = {
  refs: RepoRefEntry[];
};

export type RepoCommitsRequest = {
  owner: string;
  name: string;
  ref: string;
  skip?: number;
  limit?: number;
};

export type RepoCommitSummary = {
  sha: string;
  short_sha: string;
  subject: string;
  author_name: string;
  author_email: string;
  authored_at: string;
};

export type RepoCommitsResponse = {
  ref: string;
  commits: RepoCommitSummary[];
  skip: number;
  limit: number;
};

export type RepoCommitRequest = {
  owner: string;
  name: string;
  sha: string;
};

export type RepoDiffFile = {
  path: string;
  status: string;
  patch: string;
};

export type RepoCommitResponse = {
  sha: string;
  short_sha: string;
  subject: string;
  body: string;
  author_name: string;
  author_email: string;
  authored_at: string;
  parents: string[];
  files: RepoDiffFile[];
  truncated: boolean;
};

export type RepoCompareRequest = {
  owner: string;
  name: string;
  base: string;
  head: string;
};

export type RepoCompareResponse = {
  base: string;
  head: string;
  empty: boolean;
  truncated: boolean;
  files: RepoDiffFile[];
};

export type RepoBlameRequest = {
  owner: string;
  name: string;
  ref: string;
  path: string;
};

export type RepoBlameLine = {
  sha: string;
  author_name: string;
  authored_at: string;
  line_number: number;
  content: string;
};

export type RepoBlameResponse = {
  path: string;
  ref: string;
  lines: RepoBlameLine[];
  truncated: boolean;
};

export type RepoBranchCreateRequest = {
  owner: string;
  name: string;
  branch: string;
  start?: string | null;
};

export type RepoBranchRenameRequest = {
  owner: string;
  name: string;
  from: string;
  to: string;
};

export type RepoBranchDeleteRequest = {
  owner: string;
  name: string;
  branch: string;
};

export type RepoBranchMutationResponse = {
  branch: string;
};

export type RepoUpdateVisibilityRequest = {
  owner: string;
  name: string;
  visibility: RepoVisibility;
};

export type RepoSoftDeleteRequest = {
  owner: string;
  name: string;
  confirmName: string;
};

export type RepoSoftDeleteResponse = {
  name: string;
};

/** Per-repo collaborator permission ladder (D-ORG-02c). */
export type CollaboratorPermission = "read" | "write" | "admin";

export type RepoCollaboratorPublic = {
  user_id: string;
  username: string;
  permission: CollaboratorPermission;
  created_at: string;
};

export type RepoCollaboratorsListResponse = {
  collaborators: RepoCollaboratorPublic[];
};

export type RepoCollaboratorsAddRequest = {
  owner: string;
  name: string;
  username: string;
  permission: CollaboratorPermission;
};

export type RepoCollaboratorsUpdateRequest = {
  owner: string;
  name: string;
  user_id: string;
  permission: CollaboratorPermission;
};

export type RepoCollaboratorsRemoveRequest = {
  owner: string;
  name: string;
  user_id: string;
};

export type MemberBasePermission = "none" | "read" | "write";

export type OrgRole = "owner" | "admin" | "member";

export type OrgPublic = {
  id: string;
  slug: string;
  display_name: string;
  member_base_permission: MemberBasePermission;
  created_at: string;
  updated_at: string;
};

export type CreateOrgRequest = {
  slug: string;
  display_name?: string | null;
};

export type OrgSlugRequest = {
  slug: string;
};

export type OrgUpdateSettingsRequest = {
  slug: string;
  member_base_permission?: MemberBasePermission | null;
  display_name?: string | null;
};

export type OrgMineEntry = {
  id: string;
  slug: string;
  display_name: string;
  member_base_permission: MemberBasePermission;
  role: OrgRole;
  created_at: string;
  updated_at: string;
};

export type OrgListMineResponse = {
  orgs: OrgMineEntry[];
};

export type OrgMemberPublic = {
  user_id: string;
  username: string;
  role: OrgRole;
  created_at: string;
};

export type OrgMembersListResponse = {
  members: OrgMemberPublic[];
};

export type OrgMembersAddRequest = {
  slug: string;
  username: string;
  role: OrgRole;
};

export type OrgMembersUpdateRoleRequest = {
  slug: string;
  user_id: string;
  role: OrgRole;
};

export type OrgMembersRemoveRequest = {
  slug: string;
  user_id: string;
};

export type OrgInvitePublic = {
  id: string;
  email: string;
  role: OrgRole;
  expires_at: string;
  invited_by: string;
  created_at: string;
};

export type OrgInvitesListResponse = {
  invites: OrgInvitePublic[];
};

export type OrgInvitesCreateRequest = {
  slug: string;
  email: string;
  role: OrgRole;
};

export type OrgInvitesRevokeRequest = {
  slug: string;
  invite_id: string;
};

export type OrgInvitesAcceptRequest = {
  token: string;
  username?: string | null;
  password?: string | null;
};

export type OrgInvitesAcceptResponse = {
  org: OrgPublic;
  member: OrgMemberPublic;
};

/** Classic PAT string prefix (octanest_pat_). */
export const CLASSIC_PAT_PREFIX = "octanest_pat_" as const;
/** Fine-grained PAT string prefix (octanest_fg_). */
export const FINE_GRAINED_PAT_PREFIX = "octanest_fg_" as const;

export type PatKind = "classic" | "fine_grained";
export type ClassicPatScope = "repo";
export type FgRepoAccess = "selected" | "all";
export type ContentsPerm = "read" | "write";

export type CreateClassicPatRequest = {
  name: string;
  scopes: ClassicPatScope[];
  expires_at?: string | null;
};

export type CreateFineGrainedPatRequest = {
  name: string;
  repo_access: FgRepoAccess;
  repository_ids?: string[];
  contents: ContentsPerm;
  expires_at?: string | null;
};

export type PatListItem = {
  id: string;
  kind: PatKind;
  name: string;
  token_prefix: string;
  scopes?: ClassicPatScope[];
  contents?: ContentsPerm;
  repo_access?: FgRepoAccess;
  repository_ids?: string[];
  expires_at?: string | null;
  last_used_at?: string | null;
  last_used_ip?: string | null;
  created_at: string;
};

/** One-time create response — plaintext `token` only on create. */
export type CreatePatResponse = {
  token: string;
  item: PatListItem;
};

export type RevokePatRequest = {
  id: string;
};

export type RpcOk<T> = { ok: true; data: T };
export type RpcErr = { ok: false; error: AppError };
export type RpcResult<T> = RpcOk<T> | RpcErr;

export type CreateClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
  credentials?: RequestCredentials;
};

async function rpcCall<T>(
  opts: CreateClientOptions,
  procedure: string,
  input: unknown,
): Promise<RpcResult<T>> {
  const fetchFn = opts.fetch ?? fetch;
  const url = `${opts.baseUrl.replace(/\/$/, "")}/api/rpc`;
  const res = await fetchFn(url, {
    method: "POST",
    credentials: opts.credentials ?? "include",
    headers: {
      "content-type": "application/json",
      [RPC_VERSION_HEADER]: String(RPC_VERSION),
    },
    body: JSON.stringify({ procedure, input }),
  });
  return (await res.json()) as RpcResult<T>;
}

export function createClient(opts: CreateClientOptions) {
  return {
    system: {
      health: () => rpcCall<HealthResponse>(opts, "system.health", {}),
      echo: (input: EchoRequest) => rpcCall<EchoResponse>(opts, "system.echo", input),
      dbProbe: () => rpcCall<DbProbeResponse>(opts, "system.db_probe", {}),
    },
    auth: {
      signup: (input: SignupRequest) => rpcCall<UserPublic>(opts, "auth.signup", input),
      login: (input: LoginRequest) => rpcCall<UserPublic>(opts, "auth.login", input),
      logout: () => rpcCall<{ ok: boolean }>(opts, "auth.logout", {}),
      logoutAll: () => rpcCall<{ ok: boolean }>(opts, "auth.logout_all", {}),
      me: () => rpcCall<UserPublic>(opts, "auth.me", {}),
      providerConfig: () =>
        rpcCall<ProviderConfigPublic>(opts, "auth.provider_config", {}),
      bootstrapStatus: () =>
        rpcCall<BootstrapStatus>(opts, "auth.bootstrap_status", {}),
      bootstrapSetup: (input: BootstrapSetupRequest) =>
        rpcCall<UserPublic>(opts, "auth.bootstrap_setup", input),
      confirmAdminCredentials: (input: ConfirmAdminCredentialsRequest) =>
        rpcCall<UserPublic>(opts, "auth.confirm_admin_credentials", input),
      verify: (input: VerifyRequest) => rpcCall<UserPublic>(opts, "auth.verify", input),
      requestVerify: () => rpcCall<{ ok: boolean }>(opts, "auth.request_verify", {}),
      resendVerify: () => rpcCall<{ ok: boolean }>(opts, "auth.resend_verify", {}),
      requestPasswordReset: (input: RequestPasswordResetRequest) =>
        rpcCall<{ ok: boolean }>(opts, "auth.request_password_reset", input),
      resetPassword: (input: ResetPasswordRequest) =>
        rpcCall<UserPublic>(opts, "auth.reset_password", input),
      privilegedPing: () =>
        rpcCall<{ ok: boolean }>(opts, "auth.dev.privileged_ping", {}),
    },
    user: {
      getProfile: () => rpcCall<UserPublic>(opts, "user.get_profile", {}),
      updateProfile: (input: UpdateProfileRequest) =>
        rpcCall<UserPublic>(opts, "user.update_profile", input),
      lookup: (input: UserLookupRequest) =>
        rpcCall<UserLookupResponse>(opts, "user.lookup", input),
    },
    repo: {
      listMine: () => rpcCall<RepoListMineResponse>(opts, "repo.listMine", {}),
      createDefaults: () =>
        rpcCall<RepoCreateDefaults>(opts, "repo.createDefaults", {}),
      create: (input: CreateRepoRequest) => rpcCall<RepoPublic>(opts, "repo.create", input),
      get: (input: RepoGetRequest) => rpcCall<RepoPublic>(opts, "repo.get", input),
      tree: (input: RepoTreeRequest) => rpcCall<RepoTreeResponse>(opts, "repo.tree", input),
      blob: (input: RepoBlobRequest) => rpcCall<RepoBlobResponse>(opts, "repo.blob", input),
      refs: (input: RepoGetRequest) => rpcCall<RepoRefsResponse>(opts, "repo.refs", input),
      commits: (input: RepoCommitsRequest) =>
        rpcCall<RepoCommitsResponse>(opts, "repo.commits", input),
      commit: (input: RepoCommitRequest) =>
        rpcCall<RepoCommitResponse>(opts, "repo.commit", input),
      compare: (input: RepoCompareRequest) =>
        rpcCall<RepoCompareResponse>(opts, "repo.compare", input),
      blame: (input: RepoBlameRequest) => rpcCall<RepoBlameResponse>(opts, "repo.blame", input),
      branchCreate: (input: RepoBranchCreateRequest) =>
        rpcCall<RepoBranchMutationResponse>(opts, "repo.branchCreate", input),
      branchRename: (input: RepoBranchRenameRequest) =>
        rpcCall<RepoBranchMutationResponse>(opts, "repo.branchRename", input),
      branchDelete: (input: RepoBranchDeleteRequest) =>
        rpcCall<RepoBranchMutationResponse>(opts, "repo.branchDelete", input),
      updateVisibility: (input: RepoUpdateVisibilityRequest) =>
        rpcCall<RepoPublic>(opts, "repo.updateVisibility", input),
      softDelete: (input: RepoSoftDeleteRequest) =>
        rpcCall<RepoSoftDeleteResponse>(opts, "repo.softDelete", input),
      collaborators: {
        list: (input: RepoGetRequest) =>
          rpcCall<RepoCollaboratorsListResponse>(opts, "repo.collaborators.list", input),
        add: (input: RepoCollaboratorsAddRequest) =>
          rpcCall<RepoCollaboratorPublic>(opts, "repo.collaborators.add", input),
        update: (input: RepoCollaboratorsUpdateRequest) =>
          rpcCall<RepoCollaboratorPublic>(opts, "repo.collaborators.update", input),
        remove: (input: RepoCollaboratorsRemoveRequest) =>
          rpcCall<{ ok: boolean }>(opts, "repo.collaborators.remove", input),
      },
    },
    org: {
      create: (input: CreateOrgRequest) => rpcCall<OrgPublic>(opts, "org.create", input),
      get: (input: OrgSlugRequest) => rpcCall<OrgPublic>(opts, "org.get", input),
      listMine: () => rpcCall<OrgListMineResponse>(opts, "org.listMine", {}),
      updateSettings: (input: OrgUpdateSettingsRequest) =>
        rpcCall<OrgPublic>(opts, "org.updateSettings", input),
      members: {
        list: (input: OrgSlugRequest) =>
          rpcCall<OrgMembersListResponse>(opts, "org.members.list", input),
        add: (input: OrgMembersAddRequest) =>
          rpcCall<OrgMemberPublic>(opts, "org.members.add", input),
        updateRole: (input: OrgMembersUpdateRoleRequest) =>
          rpcCall<OrgMemberPublic>(opts, "org.members.updateRole", input),
        remove: (input: OrgMembersRemoveRequest) =>
          rpcCall<{ ok: boolean }>(opts, "org.members.remove", input),
      },
      invites: {
        create: (input: OrgInvitesCreateRequest) =>
          rpcCall<OrgInvitePublic>(opts, "org.invites.create", input),
        list: (input: OrgSlugRequest) =>
          rpcCall<OrgInvitesListResponse>(opts, "org.invites.list", input),
        revoke: (input: OrgInvitesRevokeRequest) =>
          rpcCall<{ ok: boolean }>(opts, "org.invites.revoke", input),
        accept: (input: OrgInvitesAcceptRequest) =>
          rpcCall<OrgInvitesAcceptResponse>(opts, "org.invites.accept", input),
      },
    },
    pat: {
      createClassic: (input: CreateClassicPatRequest) =>
        rpcCall<CreatePatResponse>(opts, "pat.createClassic", input),
      createFineGrained: (input: CreateFineGrainedPatRequest) =>
        rpcCall<CreatePatResponse>(opts, "pat.createFineGrained", input),
      list: () => rpcCall<PatListItem[]>(opts, "pat.list", {}),
      revoke: (input: RevokePatRequest) =>
        rpcCall<{ ok: boolean }>(opts, "pat.revoke", input),
    },
    admin: {
      auth: {
        getSettings: () =>
          rpcCall<AuthSettingsPublic>(opts, "admin.auth.get_settings", {}),
        updateSettings: (input: UpdateAuthSettingsRequest) =>
          rpcCall<AuthSettingsPublic>(opts, "admin.auth.update_settings", input),
        factoryReset: (input: FactoryResetRequest) =>
          rpcCall<FactoryResetResponse>(opts, "admin.instance.factory_reset", input),
      },
      repos: {
        gc: (input: RepoGcRequest) =>
          rpcCall<RepoGcResponse>(opts, "admin.repos.gc", input),
      },
    },
  };
}

export type OctanestClient = ReturnType<typeof createClient>;

/** TanStack Query helpers — pass a client from createClient(). */
export function systemHealthQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["system", "health"] as const,
    queryFn: async () => {
      const res = await client.system.health();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function systemEchoMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["system", "echo"] as const,
    mutationFn: async (input: EchoRequest) => {
      const res = await client.system.echo(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function systemDbProbeQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["system", "dbProbe"] as const,
    queryFn: async () => {
      const res = await client.system.dbProbe();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authMeQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["auth", "me"] as const,
    queryFn: async () => {
      const res = await client.auth.me();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authProviderConfigQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["auth", "providerConfig"] as const,
    queryFn: async () => {
      const res = await client.auth.providerConfig();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authSignupMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "signup"] as const,
    mutationFn: async (input: SignupRequest) => {
      const res = await client.auth.signup(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLoginMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "login"] as const,
    mutationFn: async (input: LoginRequest) => {
      const res = await client.auth.login(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLogoutMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "logout"] as const,
    mutationFn: async () => {
      const res = await client.auth.logout();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function authLogoutAllMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["auth", "logoutAll"] as const,
    mutationFn: async () => {
      const res = await client.auth.logoutAll();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function userGetProfileQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["user", "getProfile"] as const,
    queryFn: async () => {
      const res = await client.user.getProfile();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function userLookupQueryOptions(
  client: OctanestClient,
  input: UserLookupRequest,
) {
  return {
    queryKey: ["user", "lookup", input.prefix] as const,
    queryFn: async () => {
      const res = await client.user.lookup(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function userUpdateProfileMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["user", "updateProfile"] as const,
    mutationFn: async (input: UpdateProfileRequest) => {
      const res = await client.user.updateProfile(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoListMineQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["repo", "listMine"] as const,
    queryFn: async () => {
      const res = await client.repo.listMine();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoCreateMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["repo", "create"] as const,
    mutationFn: async (input: CreateRepoRequest) => {
      const res = await client.repo.create(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoGetQueryOptions(
  client: OctanestClient,
  input: RepoGetRequest,
) {
  return {
    queryKey: ["repo", "get", input.owner, input.name] as const,
    queryFn: async () => {
      const res = await client.repo.get(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoTreeQueryOptions(
  client: OctanestClient,
  input: RepoTreeRequest,
) {
  return {
    queryKey: [
      "repo",
      "tree",
      input.owner,
      input.name,
      input.ref,
      input.path ?? "",
    ] as const,
    queryFn: async () => {
      const res = await client.repo.tree(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoBlobQueryOptions(
  client: OctanestClient,
  input: RepoBlobRequest,
) {
  return {
    queryKey: [
      "repo",
      "blob",
      input.owner,
      input.name,
      input.ref,
      input.path,
    ] as const,
    queryFn: async () => {
      const res = await client.repo.blob(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoRefsQueryOptions(
  client: OctanestClient,
  input: RepoGetRequest,
) {
  return {
    queryKey: ["repo", "refs", input.owner, input.name] as const,
    queryFn: async () => {
      const res = await client.repo.refs(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoCommitsQueryOptions(
  client: OctanestClient,
  input: RepoCommitsRequest,
) {
  return {
    queryKey: [
      "repo",
      "commits",
      input.owner,
      input.name,
      input.ref,
      input.skip ?? 0,
      input.limit ?? 30,
    ] as const,
    queryFn: async () => {
      const res = await client.repo.commits(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoCommitQueryOptions(
  client: OctanestClient,
  input: RepoCommitRequest,
) {
  return {
    queryKey: ["repo", "commit", input.owner, input.name, input.sha] as const,
    queryFn: async () => {
      const res = await client.repo.commit(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoCompareQueryOptions(
  client: OctanestClient,
  input: RepoCompareRequest,
) {
  return {
    queryKey: [
      "repo",
      "compare",
      input.owner,
      input.name,
      input.base,
      input.head,
    ] as const,
    queryFn: async () => {
      const res = await client.repo.compare(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function repoBlameQueryOptions(
  client: OctanestClient,
  input: RepoBlameRequest,
) {
  return {
    queryKey: [
      "repo",
      "blame",
      input.owner,
      input.name,
      input.ref,
      input.path,
    ] as const,
    queryFn: async () => {
      const res = await client.repo.blame(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function patListQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["pat", "list"] as const,
    queryFn: async () => {
      const res = await client.pat.list();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function patCreateClassicMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["pat", "createClassic"] as const,
    mutationFn: async (input: CreateClassicPatRequest) => {
      const res = await client.pat.createClassic(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function patCreateFineGrainedMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["pat", "createFineGrained"] as const,
    mutationFn: async (input: CreateFineGrainedPatRequest) => {
      const res = await client.pat.createFineGrained(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function patRevokeMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["pat", "revoke"] as const,
    mutationFn: async (input: RevokePatRequest) => {
      const res = await client.pat.revoke(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function adminAuthGetSettingsQueryOptions(client: OctanestClient) {
  return {
    queryKey: ["admin", "auth", "getSettings"] as const,
    queryFn: async () => {
      const res = await client.admin.auth.getSettings();
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

export function adminAuthUpdateSettingsMutationOptions(client: OctanestClient) {
  return {
    mutationKey: ["admin", "auth", "updateSettings"] as const,
    mutationFn: async (input: UpdateAuthSettingsRequest) => {
      const res = await client.admin.auth.updateSettings(input);
      if (!res.ok) throw new Error(`${res.error.code}: ${res.error.message}`);
      return res.data;
    },
  };
}

/** Alias helpers matching CONTEXT D-21 naming. */
export const queryOptions = {
  systemHealth: systemHealthQueryOptions,
  systemDbProbe: systemDbProbeQueryOptions,
  authMe: authMeQueryOptions,
  authProviderConfig: authProviderConfigQueryOptions,
  userGetProfile: userGetProfileQueryOptions,
  repoListMine: repoListMineQueryOptions,
  repoGet: repoGetQueryOptions,
  repoTree: repoTreeQueryOptions,
  repoBlob: repoBlobQueryOptions,
  repoRefs: repoRefsQueryOptions,
  repoCommits: repoCommitsQueryOptions,
  repoCommit: repoCommitQueryOptions,
  repoCompare: repoCompareQueryOptions,
  repoBlame: repoBlameQueryOptions,
  patList: patListQueryOptions,
  adminAuthGetSettings: adminAuthGetSettingsQueryOptions,
};
export const mutationOptions = {
  systemEcho: systemEchoMutationOptions,
  authSignup: authSignupMutationOptions,
  authLogin: authLoginMutationOptions,
  authLogout: authLogoutMutationOptions,
  authLogoutAll: authLogoutAllMutationOptions,
  userUpdateProfile: userUpdateProfileMutationOptions,
  repoCreate: repoCreateMutationOptions,
  patCreateClassic: patCreateClassicMutationOptions,
  patCreateFineGrained: patCreateFineGrainedMutationOptions,
  patRevoke: patRevokeMutationOptions,
  adminAuthUpdateSettings: adminAuthUpdateSettingsMutationOptions,
};
